#Q1a
capmW23 <- read_csv("Downloads/capmW23.csv") 
#reads the capmW23 text file and creates a dataframe
attach(capmW23) 
#the capmW23 dataframe is attached to the R search path, so column vectors can 
#be accessed by name. Must be attached every session.

diff_RBC <- diff(RBC, lag = 1) 
#the difference of current RBC stock value and initial stock value
initial_RBC <- RBC[-60]
#RBC initial stock value
rtr_RBC <- diff_RBC / initial_RBC
#rate of return of RBC stock 

diff_TSXC <- diff(TSXC)
#the difference of current TSXC stock value and initial stock value
initial_TSXC <- TSXC[-60]
#initial TSXC stock value
rtr_TSXC <- diff_TSXC / initial_TSXC
#rate of return of TSXC stock

rft_GVTB <- (GVTB/100 + 1)^(1/12) - 1 
#monthly risk free rate of GVTB government bond
mod_rft <- rft_GVTB[-1]
#removing the first observation

y <- rtr_RBC - mod_rft 
x <- rtr_TSXC - mod_rft

plot(x, y, xlab = "TSXC market rate of return in excess of risk-free rate at time t",
     ylab = "rate of return of RBC stock in excess of risk-free rate at time t", 
     pch = 20, main = "RBC active return vs TSXC market active return")

#Q1b
cor(x, y) #using correlation coefficient function in R

miux <- mean(x)
miuy <- mean(y)

sxy <- sum((x - miux) * (y- miuy))
sxx <- sum((x - miux)^2)
syy <- sum((y - miuy)^2)

r <- sxy/sqrt(sxx * syy)
r
#calculated by definition, which verifies the result generated by cor function

#Q1c
capmW23.lm <- lm(y ~ x) #fitting a simple linear regression model
summary(capmW23.lm) #summarizing the data frame into one value

#Q1ei
#calculate 95% confidence interval for each coefficient in model
confint(capmW23.lm, level = 0.95)

#Q1eii
betahat <- 0.7395242
betahat_se <- 0.0935086
critical_value <- qt(0.975, 57)
critical_value

upper_bound <- betahat + betahat_se * critical_value
lower_bound <- betahat - betahat_se * critical_value

confi_int <- cbind(lower_bound, upper_bound)
confi_int

#Q1gi
ssr<- sum(residuals(capmW23.lm)^2) 
#generating the sum of squares of residuals

sigma_h <- sqrt(ssr/57)
#generating the residual standard of error 
sigma_h

#Q1gii
miuy <- mean(y)
miux <- mean(x)
alpha_h <- miuy - betahat * miux
alpha_h

#Q1giii
beta_h <- sxy/sxx
beta_h

#Q1giv
beta_hse <- sigma_h/sqrt(sxx)
beta_hse

#Q1gv
pval <- 2 * (1 - pt(7.909, 57))
pval

#Q2a
A1_variates <- read.table("Downloads/A1_variates (1).txt", header = TRUE) 
#importing text

set.seed(20908250)

beta_vec <- c(-250000, 50, -200, 12000, 200000)
#creates the beta vector
x_matrix <- as.matrix(cbind(rep(1, 24), A1_variates)) 
#creating the x_matrix
miu <- x_matrix %*% beta_vec
sigma <- 15000

residuals <- rnorm(24, 0, sigma) 
#generates 24 random values from N(0, sigma)
y_matrix <- miu + residuals #generates y_matrix
y_matrix

#Q2b
x1 <- A1_variates$size
x2 <- A1_variates$age
x3 <- A1_variates$employees
x4 <- A1_variates$col
#Define x1 x2 x3 and x4 from the A1_variates table
A1sim.lm <- lm(y_matrix ~ x1 + x2 + x3 + x4)
summary(A1sim.lm)

#Q2c
xtxinv <- solve(t(x_matrix) %*% x_matrix)
Betah <- xtxinv %*% t(x_matrix) %*% y_matrix
Betah

#Q2d
beta1hat <- 28.02
beta1hat_se <- 17.18
#obetained from summary by R function
test_sta <- qt(.975, 19)

upp_bound <- beta1hat + beta1hat_se * test_sta
low_bound <- beta1hat - beta1hat_se * test_sta
#generating 95% confidence interval
upp_bound
low_bound

CI <- cbind(low_bound, upp_bound)
CI

